tap caskroom/homebrew-cask
install brew-cask
cask install google-chrome
cask install pandoc
cask install iterm2
cask install totalfinder
cask install totalterminal
cask install totalspaces
cask install dropbox
cask install emacs
cask install evernote
cask install handbrake
cask install gyazo
cask install skype
cask install keyremap4macbook
cask install movist
cask install utorrent
cask install vlc
cask install alfred
cask install bettertouchtool
cask alfred link
update
upgrade
install ack
install ant
install asciidoc
install atk
install autoconf
install automake
install bash
install bdw-gc
install cairo
install cloog
install cloog-ppl015
install cloog018
install cmake
install crf++
install curl
install devtodo
install docbook
install docbook-xsl
install doxygen
install eigen
install faac
install ffmpeg
install fish
install fontconfig
install fontforge
install freetype
install fuse4x
install fuse4x-kext
install gcc46
install gcc47
install gd
install gdbm
install gdk-pixbuf
install gettext
#install gfortran
install git
install glib
install gmp
install gmp4
install gnu-getopt
install gnu-tar
install gnuplot
install gobject-introspection
install graphviz
install gtk+
install gtkwave
install gts
install harfbuzz
install htop-osx
install hub
install icu4c
install imagemagick
install ipmitool
install isl
install isl011
install jasper
install jenkins
install jpeg
install lame
install lesstif
install libevent
install libffi
install libiconv
install libmpc
install libmpc08
install libpng
install libtiff
install libtool
install libxml2
install libyaml
install lua
install lv
install mcrypt
install mercurial
install mhash
install mobile-shell
install mpfr
install mpfr2
install mutt
install mysql
install netpbm
install node
install opencv
install openssl
install ossp-uuid
install osxfuse
install p7zip
install pango
install pcre
install php54
install pidof
install pixman
install pkg-config
install postgresql
install potrace
install ppl011
install protobuf
install pstree
install python
install python3
install qt
install r
install rdesktop
install readline
install reattach-to-user-namespace
install redis
install rename
install sqlite
install sshfs
install suite-sparse
install swig
install tbb
install texi2html
install tgif
install the_silver_searcher
install tig
install tmux
install tokyo-cabinet
install tree
install tor
install torsocks
install unixodbc
install unrar
install w3m
install watch
install wget
install x264
install xmlto
install xpdf
install xvid
install xz
install yasm
install youtube-dl
install zlib
install zsh
install zsh-completions
install xpdf
install v8
tap kechako/zsh
install zsh-custom
install rbenv
install ruby-build
install rbenv-gem-rehash
install pyenv
